[battery]
charging_symbol = "âš¡ï¸"
# discharging_symbol = "ğŸ’€"
discharging_symbol = "ï‰‚  "
full_symbol = "ğŸ”‹"

[[battery.display]]
threshold = 10
style = "bold red"
# symbol = "aaa"

[[battery.display]]
threshold = 20
style = "bold yellow"
# symbol = "ğŸ”‹"

[[battery.display]]
threshold = 100
style = "bold green"
# discharging_symbol = "aaa"
# charging_symbol = "bbb"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "âœï¸ $count"
# modified = "ï€ $count"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[directory]
#truncate_to_repo = false
#truncation_length = 2
#repo_root_style = "green bold"
#truncation_symbol = '../'

[directory.substitutions]

#"~/git_repository" = "aaaaa"

#[cmd_duration]
#min_time = 100
#format = "underwent $millis"
